### ISSUE TITLE
cannot find the linkToBeginningThreadContext gadget

### ISSUE THREAD

**Issue by SivaDotRender** [theori-io/pwnjs#4]
`pwn.js` fails because it cannot find the following gadget: 

    'linkToBeginningThreadContext', [0x48, 0x8B, 0xC4, 0x4C, 0x89, 0x40, 0x18, 0x48, 0x89, 0x50, 0x10, 0x48, 0x89, 0x48, 0x08, 0x48, 0x83, 0x61]]

Is it possible to get some information on why this gadget is required?

Thank you in advance

**Comment by brianairb** [comment]
Hi,

We can help if we know the specifics of issues you are running into.

What version of WIndows are you running on (e.g. Windows 10 Enterprise x64 1607)? And what patch are you currently on (e.g. KB4034658)?

We use that gadget to automatically find the offsets to ThreadContext pointers in order to get the stack address dynamically. When the function we are looking for changes significantly, the gadget may not be found anymore.

**Comment by SivaDotRender** [comment]
Thank you for the prompt reply Brain!

I am currently running Windows 10 Enterprise x64 1703 (OS Build 15063.483) + Security Update KB4025342 + Chakra.dll version 11.0.15063.483

Can you let me know what version of windows/chakra pwn.js was last tested against? This way I can do some debugging on my end as well.

**Comment by SivaDotRender** [comment]
@brianairb are there any updates regarding this?

**Comment by brianairb** [comment]
@SivaDotRender Sorry that it's taken a while. We've been little busy with other work. The main issue was that the compiled code for Chakra changed slightly version to version, and we didn't have the general enough pattern to find that code. We've improved it to now support all the different patterns we know of. (Tested on 1607, 1703, 1709)

Thanks for your patience!

**Comment by SivaDotRender** [comment]
Just tested the patch and it works for me. Thank you for the excellent work @brianairb @awesie
